[package]
name = "poincare-nodes-view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
indenter = "0.3.3"
quick-xml = "0.28.2"
